cargo-features = ["strip"]

[package]
name = "browsah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
clap = {version = "3.0.0-rc.7", features = ["derive", "std"], default-features = false}
reqwest = {version = "0.11.7", features = ["blocking"]}
url = {version = "2.2.2"}

[profile.release]
strip = true
lto = true